name: Publish on gradle plugin portal

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get release tag
        id: rawtag
        uses: olegtarasov/get-tag@v2.1.2
        with:
          tagRegex: "v(.*)"
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Gradle wrapper validation
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Publish plugin
        run: ./gradlew ${{ matrix.task }} --stacktrace
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          PLUGIN_VERSION: ${{ steps.rawtag.outputs.tag }}